import { v4 as uuidv4 } from 'uuid';
import { IIntelligence } from '../models/Intelligence';

/**
 * 35 realistic mock intelligence nodes spread across the New Delhi / NCR region.
 * Used both for DB seeding and for in-memory fallback when MongoDB is unavailable.
 */
export const mockIntelligenceData: Partial<IIntelligence>[] = [
  // ── OSINT nodes (blue) ─────────────────────────────────────────────────────
  {
    nodeId: 'OSINT-001',
    type: 'OSINT',
    title: 'Suspicious Vehicle Convoy',
    latitude: 28.6139,
    longitude: 77.2090,
    timestamp: new Date('2026-04-19T10:00:00Z'),
    description: 'Three-vehicle convoy detected moving erratically near India Gate checkpoint. License plates partially obscured.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    threatLevel: 'High',
    source: 'MongoDB-OSINT',
    tags: ['vehicle', 'convoy', 'checkpoint'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-002',
    type: 'OSINT',
    title: 'Encrypted Radio Transmission',
    latitude: 28.6304,
    longitude: 77.2177,
    timestamp: new Date('2026-04-19T08:30:00Z'),
    description: 'Unidentified encrypted signal detected on restricted military frequency bands near Connaught Place.',
    imageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=400&q=80',
    threatLevel: 'Critical',
    source: 'MongoDB-OSINT',
    tags: ['signal', 'radio', 'encrypted'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-003',
    type: 'OSINT',
    title: 'Drone Activity Observed',
    latitude: 28.6562,
    longitude: 77.2410,
    timestamp: new Date('2026-04-18T22:15:00Z'),
    description: 'Unregistered quadcopter drone observed hovering over government complex for 47 minutes before disappearing.',
    imageUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=400&q=80',
    threatLevel: 'High',
    source: 'S3-OSINT',
    tags: ['drone', 'surveillance', 'UAV'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-004',
    type: 'OSINT',
    title: 'Social Media Coordination Pattern',
    latitude: 28.5921,
    longitude: 77.0460,
    timestamp: new Date('2026-04-19T06:00:00Z'),
    description: 'Spike in coded social media posts using trigger keywords. Coordination pattern matches known extremist cell communication methods.',
    threatLevel: 'Medium',
    source: 'MongoDB-OSINT',
    tags: ['social-media', 'coordination', 'digital'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-005',
    type: 'OSINT',
    title: 'Financial Transaction Anomaly',
    latitude: 28.6448,
    longitude: 77.0886,
    timestamp: new Date('2026-04-18T14:00:00Z'),
    description: 'Multiple large cash transactions flagged at Dwarka branch banks. Pattern consistent with hawala network activities.',
    imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=400&q=80',
    threatLevel: 'Medium',
    source: 'S3-OSINT',
    tags: ['financial', 'hawala', 'money'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-006',
    type: 'OSINT',
    title: 'Border Movement Pattern',
    latitude: 28.7041,
    longitude: 77.1025,
    timestamp: new Date('2026-04-17T03:30:00Z'),
    description: 'Unusual pedestrian movement detected at northern perimeter. Thermal imaging shows 8-12 individuals moving in single file.',
    threatLevel: 'Critical',
    source: 'MongoDB-OSINT',
    tags: ['border', 'movement', 'thermal'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-007',
    type: 'OSINT',
    title: 'Dark Web Forum Activity',
    latitude: 28.6692,
    longitude: 77.4538,
    timestamp: new Date('2026-04-16T18:00:00Z'),
    description: 'Noida facility name mentioned on restricted dark web forums. Thread includes operational security discussions.',
    threatLevel: 'Low',
    source: 'S3-OSINT',
    tags: ['dark-web', 'cyber', 'forum'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-008',
    type: 'OSINT',
    title: 'Suspicious Package Delivery',
    latitude: 28.5355,
    longitude: 77.3910,
    timestamp: new Date('2026-04-19T09:45:00Z'),
    description: 'Multiple non-descript packages delivered to vacant warehouse. X-ray scanners at checkpoint detected dense metallic content.',
    threatLevel: 'High',
    source: 'MongoDB-OSINT',
    tags: ['package', 'warehouse', 'metallic'],
    isActive: true,
  },

  // ── HUMINT nodes (green) ───────────────────────────────────────────────────
  {
    nodeId: 'HUMINT-001',
    type: 'HUMINT',
    title: 'Informant Report - Safe House',
    latitude: 28.5706,
    longitude: 77.3272,
    timestamp: new Date('2026-04-19T11:00:00Z'),
    description: 'Asset SIERRA-7 reports a safe house used by persons of interest. Location confirmed by two additional sources. High confidence rating.',
    imageUrl: 'https://images.unsplash.com/photo-1555636382-64f00e6ee81a?w=400&q=80',
    threatLevel: 'High',
    source: 'HUMINT-Field',
    tags: ['safe-house', 'asset', 'confirmed'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-002',
    type: 'HUMINT',
    title: 'Meeting Observed at Market',
    latitude: 28.6280,
    longitude: 77.2190,
    timestamp: new Date('2026-04-19T07:30:00Z'),
    description: 'Source ALPHA-3 observed two persons of interest conducting clandestine meeting at Lajpat Nagar market. Exchange of documents noted.',
    threatLevel: 'High',
    source: 'HUMINT-Field',
    tags: ['meeting', 'clandestine', 'documents'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-003',
    type: 'HUMINT',
    title: 'Recruitment Activity Campus',
    latitude: 28.5458,
    longitude: 77.1931,
    timestamp: new Date('2026-04-18T16:00:00Z'),
    description: 'Multiple student informants report aggressive recruitment campaigns on university campus. Individuals offering significant financial incentives.',
    threatLevel: 'Medium',
    source: 'HUMINT-Field',
    tags: ['recruitment', 'campus', 'youth'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-004',
    type: 'HUMINT',
    title: 'Weapons Cache Rumor',
    latitude: 28.6800,
    longitude: 77.3200,
    timestamp: new Date('2026-04-17T20:00:00Z'),
    description: 'Local informant claims weapons cache stored in abandoned factory complex. Information unconfirmed — corroboration required.',
    imageUrl: 'https://images.unsplash.com/photo-1566847438217-76e82d3680d6?w=400&q=80',
    threatLevel: 'Critical',
    source: 'HUMINT-Field',
    tags: ['weapons', 'cache', 'unconfirmed'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-005',
    type: 'HUMINT',
    title: 'Suspected Camp - Rural',
    latitude: 28.4089,
    longitude: 77.3178,
    timestamp: new Date('2026-04-16T05:00:00Z'),
    description: 'Farmer reported unusual night activity at abandoned farm. Sounds of equipment and multiple vehicles observed over 3 nights.',
    threatLevel: 'Medium',
    source: 'HUMINT-Field',
    tags: ['camp', 'rural', 'night-activity'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-006',
    type: 'HUMINT',
    title: 'Insider Threat - Identified',
    latitude: 28.6200,
    longitude: 77.0800,
    timestamp: new Date('2026-04-15T13:00:00Z'),
    description: 'Source BRAVO-9 identifies government employee suspected of leaking classified documents. Full profile submitted to counterintelligence.',
    threatLevel: 'Critical',
    source: 'HUMINT-CI',
    tags: ['insider', 'leak', 'classified'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-007',
    type: 'HUMINT',
    title: 'Infrastructure Reconnaissance',
    latitude: 28.5800,
    longitude: 77.1500,
    timestamp: new Date('2026-04-14T10:30:00Z'),
    description: 'Security guard reports unfamiliar individuals photographing power substation infrastructure on multiple occasions this week.',
    threatLevel: 'Medium',
    source: 'HUMINT-Field',
    tags: ['infrastructure', 'recon', 'photography'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-008',
    type: 'HUMINT',
    title: 'Foreign Handler Contact',
    latitude: 28.5518,
    longitude: 77.2677,
    timestamp: new Date('2026-04-13T19:00:00Z'),
    description: 'Double agent reports contact from suspected foreign intelligence handler at Hauz Khas hotel. Meeting lasted 2 hours.',
    imageUrl: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&q=80',
    threatLevel: 'High',
    source: 'HUMINT-CI',
    tags: ['foreign', 'handler', 'hotel'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-009',
    type: 'HUMINT',
    title: 'Safe Route Identified',
    latitude: 28.7200,
    longitude: 77.1800,
    timestamp: new Date('2026-04-12T08:00:00Z'),
    description: 'Asset confirms primary exfiltration route used by network. Route runs through Rohini sector avoiding CCTV blind spots.',
    threatLevel: 'Low',
    source: 'HUMINT-Field',
    tags: ['route', 'exfiltration', 'confirmed'],
    isActive: true,
  },

  // ── IMINT nodes (red) ─────────────────────────────────────────────────────
  {
    nodeId: 'IMINT-001',
    type: 'IMINT',
    title: 'Satellite Image - Vehicle Staging',
    latitude: 28.6100,
    longitude: 77.2400,
    timestamp: new Date('2026-04-19T05:30:00Z'),
    description: 'High-resolution satellite capture shows 15+ vehicles staged in formation at open lot. Unusual for time of day.',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80',
    threatLevel: 'High',
    source: 'IMINT-SAT',
    tags: ['satellite', 'vehicles', 'staging'],
    isActive: true,
  },
  {
    nodeId: 'IMINT-002',
    type: 'IMINT',
    title: 'Aerial Recon - Construction',
    latitude: 28.6600,
    longitude: 77.1600,
    timestamp: new Date('2026-04-18T12:00:00Z'),
    description: 'UAV imagery reveals unauthorized construction activity at classified buffer zone. Structures match known base-camp configurations.',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=400&q=80',
    threatLevel: 'Critical',
    source: 'IMINT-UAV',
    tags: ['construction', 'unauthorized', 'basecamp'],
    isActive: true,
  },
  {
    nodeId: 'IMINT-003',
    type: 'IMINT',
    title: 'Thermal Anomaly Detected',
    latitude: 28.5900,
    longitude: 77.2900,
    timestamp: new Date('2026-04-18T02:00:00Z'),
    description: 'FLIR satellite data shows significant heat signature in otherwise vacant warehouse district. Consistent with generator or heavy equipment operation.',
    imageUrl: 'https://images.unsplash.com/photo-1611003229186-2f0a3c2ad0a0?w=400&q=80',
    threatLevel: 'High',
    source: 'IMINT-SAT',
    tags: ['thermal', 'FLIR', 'warehouse'],
    isActive: true,
  },
  {
    nodeId: 'IMINT-004',
    type: 'IMINT',
    title: 'Tunnel Entry Point',
    latitude: 28.6350,
    longitude: 77.0500,
    timestamp: new Date('2026-04-17T16:30:00Z'),
    description: 'Aerial photography reveals disturbed earth pattern consistent with underground tunnel construction. Entry point marked with concealed vegetation.',
    imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&q=80',
    threatLevel: 'Critical',
    source: 'IMINT-UAV',
    tags: ['tunnel', 'underground', 'concealed'],
    isActive: true,
  },
  {
    nodeId: 'IMINT-005',
    type: 'IMINT',
    title: 'Ship Movement - Yamuna Ghat',
    latitude: 28.6750,
    longitude: 77.2500,
    timestamp: new Date('2026-04-16T21:00:00Z'),
    description: 'Night-vision imagery captures unauthorized vessel operating on river at Yamuna Ghat. Vessel not registered in maritime database.',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
    threatLevel: 'Medium',
    source: 'IMINT-SAT',
    tags: ['vessel', 'river', 'unauthorized'],
    isActive: true,
  },
  {
    nodeId: 'IMINT-006',
    type: 'IMINT',
    title: 'Ground Force Assembly',
    latitude: 28.5200,
    longitude: 77.1200,
    timestamp: new Date('2026-04-15T04:00:00Z'),
    description: 'Pre-dawn imagery shows assembly of approximately 40 individuals in agricultural field. Movement patterns suggest coordinated tactical exercise.',
    imageUrl: 'https://images.unsplash.com/photo-1608841828548-a76a5b8b1ecb?w=400&q=80',
    threatLevel: 'Critical',
    source: 'IMINT-SAT',
    tags: ['assembly', 'tactical', 'ground-force'],
    isActive: true,
  },
  {
    nodeId: 'IMINT-007',
    type: 'IMINT',
    title: 'Antenna Array Installation',
    latitude: 28.7100,
    longitude: 77.0900,
    timestamp: new Date('2026-04-14T09:00:00Z'),
    description: 'Rooftop imagery shows rapid installation of directional antenna arrays on residential building. Array orientation targets military communication frequencies.',
    imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&q=80',
    threatLevel: 'High',
    source: 'IMINT-UAV',
    tags: ['antenna', 'signals', 'residential'],
    isActive: true,
  },
  {
    nodeId: 'IMINT-008',
    type: 'IMINT',
    title: 'Chemical Plume Signature',
    latitude: 28.4900,
    longitude: 77.4100,
    timestamp: new Date('2026-04-13T11:30:00Z'),
    description: 'Multispectral satellite analysis detects unusual chemical spectral signature over industrial district. Matches known precursor materials for explosives.',
    imageUrl: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=400&q=80',
    threatLevel: 'Critical',
    source: 'IMINT-SAT',
    tags: ['chemical', 'spectral', 'industrial'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-009',
    type: 'OSINT',
    title: 'Network Intrusion Attempt',
    latitude: 28.6050,
    longitude: 77.3300,
    timestamp: new Date('2026-04-19T01:00:00Z'),
    description: 'IDS/IPS logs show coordinated intrusion attempt targeting government network infrastructure from distributed IP ranges.',
    threatLevel: 'High',
    source: 'S3-OSINT',
    tags: ['cyber', 'intrusion', 'network'],
    isActive: true,
  },
  {
    nodeId: 'HUMINT-010',
    type: 'HUMINT',
    title: 'Explosives Storage Tip',
    latitude: 28.7350,
    longitude: 77.2800,
    timestamp: new Date('2026-04-11T14:00:00Z'),
    description: 'Anonymous tip received via secure hotline reports explosives storage in basement of residential complex in Bawana.',
    threatLevel: 'Critical',
    source: 'HUMINT-Hotline',
    tags: ['explosives', 'basement', 'tip'],
    isActive: true,
  },
  {
    nodeId: 'IMINT-009',
    type: 'IMINT',
    title: 'Perimeter Surveillance Grid',
    latitude: 28.5500,
    longitude: 77.0200,
    timestamp: new Date('2026-04-10T06:00:00Z'),
    description: 'Grid of concealed surveillance cameras detected by drone imaging along 2km stretch of perimeter fence. Cameras feed to unknown receiver.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    threatLevel: 'High',
    source: 'IMINT-UAV',
    tags: ['camera', 'surveillance', 'perimeter'],
    isActive: true,
  },
  {
    nodeId: 'OSINT-010',
    type: 'OSINT',
    title: 'Propaganda Material Distribution',
    latitude: 28.6450,
    longitude: 77.3750,
    timestamp: new Date('2026-04-09T08:00:00Z'),
    description: 'Large quantities of printed propaganda materials discovered in transit vehicle during routine check at Ghaziabad border crossing.',
    threatLevel: 'Low',
    source: 'MongoDB-OSINT',
    tags: ['propaganda', 'transit', 'print'],
    isActive: true,
  },
];
